//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sinema.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ad Soyad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string adsoyad {
            get {
                return ResourceManager.GetString("adsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Afiş Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string afişekle {
            get {
                return ResourceManager.GetString("afişekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sinema Bilet Satış Otomasyonu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bilet {
            get {
                return ResourceManager.GetString("bilet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilet Fiyatları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string biletfiyat {
            get {
                return ResourceManager.GetString("biletfiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilet İptal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string biletiptal {
            get {
                return ResourceManager.GetString("biletiptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilet Sat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string biletsat {
            get {
                return ResourceManager.GetString("biletsat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilet Satıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string biletsatildi {
            get {
                return ResourceManager.GetString("biletsatildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilet Satış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string biletsatış {
            get {
                return ResourceManager.GetString("biletsatış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilet Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bilettipi {
            get {
                return ResourceManager.GetString("bilettipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgiler Güncellendi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bilgilerguncellendi {
            get {
                return ResourceManager.GetString("bilgilerguncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgileri Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bilgileriguncelle {
            get {
                return ResourceManager.GetString("bilgileriguncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dikkat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string dikkat {
            get {
                return ResourceManager.GetString("dikkat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ekle {
            get {
                return ResourceManager.GetString("ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film Başarıyla Eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string eklendi {
            get {
                return ResourceManager.GetString("eklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eklemek İstediğiniz Salon İsmini Girin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ekleneceksalonid {
            get {
                return ResourceManager.GetString("ekleneceksalonid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film ekleme başarısız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string eklenmedi {
            get {
                return ResourceManager.GetString("eklenmedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string film {
            get {
                return ResourceManager.GetString("film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmadi {
            get {
                return ResourceManager.GetString("filmadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmbilgileri {
            get {
                return ResourceManager.GetString("filmbilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmekle {
            get {
                return ResourceManager.GetString("filmekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film ID benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmid {
            get {
                return ResourceManager.GetString("filmid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmislem {
            get {
                return ResourceManager.GetString("filmislem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filmleri Listele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmlerilistele {
            get {
                return ResourceManager.GetString("filmlerilistele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film Silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmsilindi {
            get {
                return ResourceManager.GetString("filmsilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filmin Süresi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmsüresi {
            get {
                return ResourceManager.GetString("filmsüresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmtarihi {
            get {
                return ResourceManager.GetString("filmtarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film Türü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmtürü {
            get {
                return ResourceManager.GetString("filmtürü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film Ülke benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string filmulke {
            get {
                return ResourceManager.GetString("filmulke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiyat Güncellendi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string fiyatguncellendi {
            get {
                return ResourceManager.GetString("fiyatguncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geriye dönük işlem yapılamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string geriyedonukislem {
            get {
                return ResourceManager.GetString("geriyedonukislem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string guncelle {
            get {
                return ResourceManager.GetString("guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boş alan bırakmayınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hata {
            get {
                return ResourceManager.GetString("hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hataa {
            get {
                return ResourceManager.GetString("hataa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem Başarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string işlembaşarılı {
            get {
                return ResourceManager.GetString("işlembaşarılı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem yapılsın mı? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string islemyap {
            get {
                return ResourceManager.GetString("islemyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kayıt {
            get {
                return ResourceManager.GetString("kayıt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Koltuk İptali Başarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string koltukiptalbasarili {
            get {
                return ResourceManager.GetString("koltukiptalbasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Koltuk No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string koltukno {
            get {
                return ResourceManager.GetString("koltukno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil Seçimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Öğrenci Bilet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ogrenci {
            get {
                return ResourceManager.GetString("ogrenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturumu Kapat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string oturumukapat {
            get {
                return ResourceManager.GetString("oturumukapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oyuncular benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string oyuncular {
            get {
                return ResourceManager.GetString("oyuncular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Özet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string özet {
            get {
                return ResourceManager.GetString("özet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   P      E        R       D       E benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string perde {
            get {
                return ResourceManager.GetString("perde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personel {
            get {
                return ResourceManager.GetString("personel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Bilgilerini Güncelle. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelbilgi {
            get {
                return ResourceManager.GetString("personelbilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelbilgileri {
            get {
                return ResourceManager.GetString("personelbilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelekle {
            get {
                return ResourceManager.GetString("personelekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personeleklendi {
            get {
                return ResourceManager.GetString("personeleklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Eklenemedi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personeleklenemedi {
            get {
                return ResourceManager.GetString("personeleklenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelislem {
            get {
                return ResourceManager.GetString("personelislem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelsil {
            get {
                return ResourceManager.GetString("personelsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelsilindi {
            get {
                return ResourceManager.GetString("personelsilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Silinemedi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelsilinemedi {
            get {
                return ResourceManager.GetString("personelsilinemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rezerve Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string rezerveet {
            get {
                return ResourceManager.GetString("rezerveet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string salon {
            get {
                return ResourceManager.GetString("salon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string salonbilgileri {
            get {
                return ResourceManager.GetString("salonbilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon Eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string saloneklendi {
            get {
                return ResourceManager.GetString("saloneklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon Ekle ve Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string saloneklevesil {
            get {
                return ResourceManager.GetString("saloneklevesil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string salonno {
            get {
                return ResourceManager.GetString("salonno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon Silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string salonsilindi {
            get {
                return ResourceManager.GetString("salonsilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string satis {
            get {
                return ResourceManager.GetString("satis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satış ID benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string satisid {
            get {
                return ResourceManager.GetString("satisid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satış Listele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string satislistele {
            get {
                return ResourceManager.GetString("satislistele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satış Listele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string satışlistele {
            get {
                return ResourceManager.GetString("satışlistele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seans benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seans {
            get {
                return ResourceManager.GetString("seans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seans Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seansekle {
            get {
                return ResourceManager.GetString("seansekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seans Ekleme Başarılı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seanseklemebasarili {
            get {
                return ResourceManager.GetString("seanseklemebasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seansı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seansı {
            get {
                return ResourceManager.GetString("seansı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seans ID benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seansid {
            get {
                return ResourceManager.GetString("seansid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seanslar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seanslar {
            get {
                return ResourceManager.GetString("seanslar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seans Seçimi Yapmadınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seanssecimiyapmadın {
            get {
                return ResourceManager.GetString("seanssecimiyapmadın", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seans Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seanssil {
            get {
                return ResourceManager.GetString("seanssil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seans Silindi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string seanssilindi {
            get {
                return ResourceManager.GetString("seanssilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinecek film ID numarasını giriniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silfilm {
            get {
                return ResourceManager.GetString("silfilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinecek personelin ID&apos;si benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinecekpersonel {
            get {
                return ResourceManager.GetString("silinecekpersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinecek Salon ID&apos;si Girin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silineceksalonid {
            get {
                return ResourceManager.GetString("silineceksalonid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinecek seansın ID&apos;sini girin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinecekseansid {
            get {
                return ResourceManager.GetString("silinecekseansid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film silme iptal edildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silmeptal {
            get {
                return ResourceManager.GetString("silmeptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tam bilet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tambilet {
            get {
                return ResourceManager.GetString("tambilet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tarih {
            get {
                return ResourceManager.GetString("tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Satış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string toplamsatış {
            get {
                return ResourceManager.GetString("toplamsatış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm Satış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tümsatış {
            get {
                return ResourceManager.GetString("tümsatış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ücret benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ucret {
            get {
                return ResourceManager.GetString("ucret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgilerini kontrol edin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string uyari {
            get {
                return ResourceManager.GetString("uyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üye ID benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string uyeid {
            get {
                return ResourceManager.GetString("uyeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vizyondaki Filmler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string vizyondakifilmler {
            get {
                return ResourceManager.GetString("vizyondakifilmler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vizyona Giriş Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string vizyontarih {
            get {
                return ResourceManager.GetString("vizyontarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yapım Yılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yapımyılı {
            get {
                return ResourceManager.GetString("yapımyılı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yönetici Paneli benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yoneticipaneli {
            get {
                return ResourceManager.GetString("yoneticipaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yönetmen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yonetmen {
            get {
                return ResourceManager.GetString("yonetmen", resourceCulture);
            }
        }
    }
}
